# Generated by Django 3.2.9 on 2021-11-08 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateTimeField()),
                ('from_name', models.CharField(max_length=200)),
                ('from_phone', models.CharField(max_length=200)),
                ('from_adress', models.CharField(max_length=200)),
                ('from_office', models.CharField(max_length=200)),
                ('to_name', models.CharField(max_length=200)),
                ('to_phone', models.CharField(max_length=200)),
                ('to_adress', models.CharField(max_length=200)),
                ('to_office', models.CharField(max_length=200)),
                ('order_id', models.CharField(max_length=200)),
                ('payment_due', models.DateTimeField()),
                ('booking_mode', models.CharField(max_length=200)),
                ('shipment_insurance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PackageTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField(default=0)),
                ('tracking_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='sflogisticsapp.trackingdetails')),
            ],
        ),
    ]
