# Generated by Django 3.2.9 on 2021-11-08 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sflogisticsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('services', models.CharField(max_length=200)),
                ('goods_type', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
                ('pickup_date_time', models.DateTimeField()),
                ('description', models.CharField(max_length=200)),
                ('consignee_name', models.CharField(max_length=200)),
                ('consignee_phone', models.CharField(max_length=200)),
                ('consignee_address', models.CharField(max_length=200)),
                ('shipper_name', models.CharField(max_length=200)),
                ('shipper_address', models.CharField(max_length=200)),
                ('order_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='PackageTable',
            new_name='Packages',
        ),
        migrations.RenameModel(
            old_name='TrackingDetails',
            new_name='Receipt',
        ),
        migrations.CreateModel(
            name='TrackingRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freight', models.CharField(max_length=200)),
                ('last_location', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=200)),
                ('current_status', models.CharField(max_length=200)),
                ('booking_mode', models.CharField(max_length=200)),
                ('additional_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='sflogisticsapp.trackinginfo')),
            ],
        ),
    ]
