# Generated by Django 3.2.9 on 2021-11-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sflogisticsapp', '0002_auto_20211108_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingroute',
            name='booking_mode',
        ),
        migrations.RemoveField(
            model_name='trackingroute',
            name='current_status',
        ),
        migrations.AddField(
            model_name='trackinginfo',
            name='booking_mode',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackinginfo',
            name='current_status',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
